country = "Canada"
product = "Liso-cel"
accountName = "Quebec Hospital"
siteAddress = "123 Toronto Way"
siteCity = "Toronto"
siteState = "NT"
siteZip = "31765"

RRPhone = "9873324891"
RRCredentials = "Nurse"
RRFax = "2234567891"
RRFirstName = "Clint"
RRLastName = "Romanov"

FMRFirstName = "Jules"
FMRLastName = "Verne"
FMRPhone = "2346783264"
FMRTitle = "MSL"

KAMTitle = "SL"
KAMFirstName = "Anton"
KAMLastName = "Bernadette"
KAMPhone = "9876545321"
KAMEmail = "TestKAMEmail@bms.com"
#FRAUATTEST@protonmail.com / Rules@1234