accountName = "Hero Hospital"
siteAddress = "117 Hero Way"
siteCity = "Summit"
siteZip = "65754"
siteState = "NJ"
country = "USA"
product = "Ide-cel;Liso-cel"

AffilEntityName = "Hero Clinic"
Affil_AccountType = "Clinic"
Affil_AddressLine1 = "117 Hero Way"
Affil_City = "Summit"
Affil_State = "NJ"
Affil_Zip = "65757"
Affil_Country = "USA"

RRCredentials = "Dr."
RRFirstName = "Jerry"
RRLastName = "Armstrong"
RRPhone = "9887878765"
RRFax = "9876767654"
#RREmail = RRFirstName + "." + RRLastName + "@bms.com"

FMRFirstName = "Charles"
FMRLastName = "Manning"
FMRTitle = "MSL"
FMRPhone = "1234567890"
#FMREmail = FMRFirstName + "." + FMRLastName + "@bms.com"

KAMFirstName = "Gen"
KAMLastName = "Tong"
KAMTitle = "CTAM"
KAMPhone = "1112223334"
KAMEmail = KAMFirstName + "." + KAMLastName + "@bms.com"

LEMFirstName = "Reed"
LEMLastName = "Smith"
LEMEmail = LEMFirstName + "." + LEMLastName + "@bms.com"
LEMTitle = "LEM"
LEMPhone = "1200567000"
